services:
  app:
    build: .
    container_name: Backend
    env_file:
      - .env.docker
    environment:
      DOCKER: 'true'
    depends_on:
      - db
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    command: sh ./entrypoint.sh

  db:
    image: postgres:15
    container_name: Postgres
    restart: always
    env_file:
      - .env.docker
    ports:
      - '5432:5432'
    volumes:
      - taskManager360_postgres_volume:/var/lib/postgresql/data

volumes:
  taskManager360_postgres_volume: